spring:
  data:
    mongodb:
      database=${MONGO_INIT_DATABASE}
      host=${MONGO_HOST}
      port=27018
      repositories.enabled=true


#spring.data.mongodb.database=stok_bilgisi
#spring.data.mongodb.uri=mongodb://localhost:27017

#Logging level changed to DEBUG.
logging:
  level:
    tr.edu.anadolu.productlistapp=DEBUG